<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppBundleDocumentSiteHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['rootUrl']) || (! empty($this->class->fieldMappings['rootUrl']['nullable']) && array_key_exists('rootUrl', $data))) {
            $value = $data['rootUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['rootUrl']->setValue($document, $return);
            $hydratedData['rootUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['categoriesUrl']) || (! empty($this->class->fieldMappings['categoriesUrl']['nullable']) && array_key_exists('categoriesUrl', $data))) {
            $value = $data['categoriesUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['categoriesUrl']->setValue($document, $return);
            $hydratedData['categoriesUrl'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['categoriesDefaultPageCount']) || (! empty($this->class->fieldMappings['categoriesDefaultPageCount']['nullable']) && array_key_exists('categoriesDefaultPageCount', $data))) {
            $value = $data['categoriesDefaultPageCount'];
            if ($value !== null) {
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['categoriesDefaultPageCount']->setValue($document, $return);
            $hydratedData['categoriesDefaultPageCount'] = $return;
        }

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }
        return $hydratedData;
    }
}